import './globals.css'
import { AuthProvider } from './providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body > <AuthProvider> {children} </AuthProvider> </body>
    </html>
  )
}
